// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"AIChat/internal/biz"
	"AIChat/internal/conf"
	"AIChat/internal/data"
	"AIChat/internal/server"
	"AIChat/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	aiChatRepo := data.NewAIChatRepo(dataData)
	aiChatUsecase := biz.NewAIChatUsecase(aiChatRepo)
	chatService := service.NewChatService(aiChatUsecase)
	grpcServer := server.NewGRPCServer(confServer, chatService, logger)
	app := newApp(logger, grpcServer, dataData)
	return app, func() {
		cleanup()
	}, nil
}
