// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.24.3
// source: api/AI_Cloudflare/AI_Cloudflare.proto

package AI_Cloudflare

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AISummarizationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArticleText []byte `protobuf:"bytes,1,opt,name=ArticleText,proto3" json:"ArticleText,omitempty"`
}

func (x *AISummarizationRequest) Reset() {
	*x = AISummarizationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_AI_Cloudflare_AI_Cloudflare_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AISummarizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AISummarizationRequest) ProtoMessage() {}

func (x *AISummarizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_AI_Cloudflare_AI_Cloudflare_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AISummarizationRequest.ProtoReflect.Descriptor instead.
func (*AISummarizationRequest) Descriptor() ([]byte, []int) {
	return file_api_AI_Cloudflare_AI_Cloudflare_proto_rawDescGZIP(), []int{0}
}

func (x *AISummarizationRequest) GetArticleText() []byte {
	if x != nil {
		return x.ArticleText
	}
	return nil
}

type AISummarizationReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TextAbstract string `protobuf:"bytes,1,opt,name=TextAbstract,proto3" json:"TextAbstract,omitempty"`
}

func (x *AISummarizationReply) Reset() {
	*x = AISummarizationReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_AI_Cloudflare_AI_Cloudflare_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AISummarizationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AISummarizationReply) ProtoMessage() {}

func (x *AISummarizationReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_AI_Cloudflare_AI_Cloudflare_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AISummarizationReply.ProtoReflect.Descriptor instead.
func (*AISummarizationReply) Descriptor() ([]byte, []int) {
	return file_api_AI_Cloudflare_AI_Cloudflare_proto_rawDescGZIP(), []int{1}
}

func (x *AISummarizationReply) GetTextAbstract() string {
	if x != nil {
		return x.TextAbstract
	}
	return ""
}

var File_api_AI_Cloudflare_AI_Cloudflare_proto protoreflect.FileDescriptor

var file_api_AI_Cloudflare_AI_Cloudflare_proto_rawDesc = []byte{
	0x0a, 0x25, 0x61, 0x70, 0x69, 0x2f, 0x41, 0x49, 0x5f, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x66, 0x6c,
	0x61, 0x72, 0x65, 0x2f, 0x41, 0x49, 0x5f, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x66, 0x6c, 0x61, 0x72,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x49, 0x5f,
	0x43, 0x6c, 0x6f, 0x75, 0x64, 0x66, 0x6c, 0x61, 0x72, 0x65, 0x22, 0x3a, 0x0a, 0x16, 0x41, 0x49,
	0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x54,
	0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x41, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x54, 0x65, 0x78, 0x74, 0x22, 0x3a, 0x0a, 0x14, 0x41, 0x49, 0x53, 0x75, 0x6d, 0x6d,
	0x61, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x22,
	0x0a, 0x0c, 0x54, 0x65, 0x78, 0x74, 0x41, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x54, 0x65, 0x78, 0x74, 0x41, 0x62, 0x73, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x32, 0x7d, 0x0a, 0x0c, 0x41, 0x49, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x66, 0x6c, 0x61,
	0x72, 0x65, 0x12, 0x6d, 0x0a, 0x15, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x41, 0x49, 0x53, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x41, 0x49, 0x5f, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x66, 0x6c, 0x61, 0x72, 0x65, 0x2e,
	0x41, 0x49, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x49, 0x5f,
	0x43, 0x6c, 0x6f, 0x75, 0x64, 0x66, 0x6c, 0x61, 0x72, 0x65, 0x2e, 0x41, 0x49, 0x53, 0x75, 0x6d,
	0x6d, 0x61, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x30,
	0x01, 0x42, 0x2c, 0x5a, 0x2a, 0x41, 0x49, 0x5f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x41, 0x49, 0x5f, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x66, 0x6c, 0x61, 0x72,
	0x65, 0x3b, 0x41, 0x49, 0x5f, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x66, 0x6c, 0x61, 0x72, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_AI_Cloudflare_AI_Cloudflare_proto_rawDescOnce sync.Once
	file_api_AI_Cloudflare_AI_Cloudflare_proto_rawDescData = file_api_AI_Cloudflare_AI_Cloudflare_proto_rawDesc
)

func file_api_AI_Cloudflare_AI_Cloudflare_proto_rawDescGZIP() []byte {
	file_api_AI_Cloudflare_AI_Cloudflare_proto_rawDescOnce.Do(func() {
		file_api_AI_Cloudflare_AI_Cloudflare_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_AI_Cloudflare_AI_Cloudflare_proto_rawDescData)
	})
	return file_api_AI_Cloudflare_AI_Cloudflare_proto_rawDescData
}

var file_api_AI_Cloudflare_AI_Cloudflare_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_AI_Cloudflare_AI_Cloudflare_proto_goTypes = []any{
	(*AISummarizationRequest)(nil), // 0: api.AI_Cloudflare.AISummarizationRequest
	(*AISummarizationReply)(nil),   // 1: api.AI_Cloudflare.AISummarizationReply
}
var file_api_AI_Cloudflare_AI_Cloudflare_proto_depIdxs = []int32{
	0, // 0: api.AI_Cloudflare.AICloudflare.StreamAISummarization:input_type -> api.AI_Cloudflare.AISummarizationRequest
	1, // 1: api.AI_Cloudflare.AICloudflare.StreamAISummarization:output_type -> api.AI_Cloudflare.AISummarizationReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_AI_Cloudflare_AI_Cloudflare_proto_init() }
func file_api_AI_Cloudflare_AI_Cloudflare_proto_init() {
	if File_api_AI_Cloudflare_AI_Cloudflare_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_AI_Cloudflare_AI_Cloudflare_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AISummarizationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_AI_Cloudflare_AI_Cloudflare_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AISummarizationReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_AI_Cloudflare_AI_Cloudflare_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_AI_Cloudflare_AI_Cloudflare_proto_goTypes,
		DependencyIndexes: file_api_AI_Cloudflare_AI_Cloudflare_proto_depIdxs,
		MessageInfos:      file_api_AI_Cloudflare_AI_Cloudflare_proto_msgTypes,
	}.Build()
	File_api_AI_Cloudflare_AI_Cloudflare_proto = out.File
	file_api_AI_Cloudflare_AI_Cloudflare_proto_rawDesc = nil
	file_api_AI_Cloudflare_AI_Cloudflare_proto_goTypes = nil
	file_api_AI_Cloudflare_AI_Cloudflare_proto_depIdxs = nil
}
