// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.24.3
// source: api/stat_user/stat_user.proto

package stat_user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DayStatistics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreatedAt string `protobuf:"bytes,1,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	Pv        uint64 `protobuf:"varint,2,opt,name=Pv,proto3" json:"Pv,omitempty"`
	Uv        uint64 `protobuf:"varint,3,opt,name=Uv,proto3" json:"Uv,omitempty"`
	Uid       uint64 `protobuf:"varint,4,opt,name=Uid,proto3" json:"Uid,omitempty"`
}

func (x *DayStatistics) Reset() {
	*x = DayStatistics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_stat_user_stat_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DayStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayStatistics) ProtoMessage() {}

func (x *DayStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_api_stat_user_stat_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayStatistics.ProtoReflect.Descriptor instead.
func (*DayStatistics) Descriptor() ([]byte, []int) {
	return file_api_stat_user_stat_user_proto_rawDescGZIP(), []int{0}
}

func (x *DayStatistics) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DayStatistics) GetPv() uint64 {
	if x != nil {
		return x.Pv
	}
	return 0
}

func (x *DayStatistics) GetUv() uint64 {
	if x != nil {
		return x.Uv
	}
	return 0
}

func (x *DayStatistics) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetUserSevenDaysStatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint64 `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
}

func (x *GetUserSevenDaysStatRequest) Reset() {
	*x = GetUserSevenDaysStatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_stat_user_stat_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserSevenDaysStatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSevenDaysStatRequest) ProtoMessage() {}

func (x *GetUserSevenDaysStatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stat_user_stat_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSevenDaysStatRequest.ProtoReflect.Descriptor instead.
func (*GetUserSevenDaysStatRequest) Descriptor() ([]byte, []int) {
	return file_api_stat_user_stat_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserSevenDaysStatRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetUserSevenDaysStatReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SevenDaysData []*DayStatistics `protobuf:"bytes,1,rep,name=SevenDaysData,proto3" json:"SevenDaysData,omitempty"`
	Code          uint32           `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg           string           `protobuf:"bytes,3,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *GetUserSevenDaysStatReply) Reset() {
	*x = GetUserSevenDaysStatReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_stat_user_stat_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserSevenDaysStatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSevenDaysStatReply) ProtoMessage() {}

func (x *GetUserSevenDaysStatReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_stat_user_stat_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSevenDaysStatReply.ProtoReflect.Descriptor instead.
func (*GetUserSevenDaysStatReply) Descriptor() ([]byte, []int) {
	return file_api_stat_user_stat_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserSevenDaysStatReply) GetSevenDaysData() []*DayStatistics {
	if x != nil {
		return x.SevenDaysData
	}
	return nil
}

func (x *GetUserSevenDaysStatReply) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetUserSevenDaysStatReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type SetUserStatInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*DayStatistics `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (x *SetUserStatInfoRequest) Reset() {
	*x = SetUserStatInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_stat_user_stat_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUserStatInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserStatInfoRequest) ProtoMessage() {}

func (x *SetUserStatInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stat_user_stat_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserStatInfoRequest.ProtoReflect.Descriptor instead.
func (*SetUserStatInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_stat_user_stat_user_proto_rawDescGZIP(), []int{3}
}

func (x *SetUserStatInfoRequest) GetData() []*DayStatistics {
	if x != nil {
		return x.Data
	}
	return nil
}

type SetUserStatInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code uint32 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *SetUserStatInfoReply) Reset() {
	*x = SetUserStatInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_stat_user_stat_user_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUserStatInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserStatInfoReply) ProtoMessage() {}

func (x *SetUserStatInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_stat_user_stat_user_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserStatInfoReply.ProtoReflect.Descriptor instead.
func (*SetUserStatInfoReply) Descriptor() ([]byte, []int) {
	return file_api_stat_user_stat_user_proto_rawDescGZIP(), []int{4}
}

func (x *SetUserStatInfoReply) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SetUserStatInfoReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_api_stat_user_stat_user_proto protoreflect.FileDescriptor

var file_api_stat_user_stat_user_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2f,
	0x73, 0x74, 0x61, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0d, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x22, 0x5f,
	0x0a, 0x0d, 0x44, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x50, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x50, 0x76, 0x12, 0x0e, 0x0a,
	0x02, 0x55, 0x76, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x55, 0x76, 0x12, 0x10, 0x0a,
	0x03, 0x55, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x55, 0x69, 0x64, 0x22,
	0x2f, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x76, 0x65, 0x6e, 0x44,
	0x61, 0x79, 0x73, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x55, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x55, 0x69, 0x64,
	0x22, 0x85, 0x01, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x76, 0x65,
	0x6e, 0x44, 0x61, 0x79, 0x73, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x42,
	0x0a, 0x0d, 0x53, 0x65, 0x76, 0x65, 0x6e, 0x44, 0x61, 0x79, 0x73, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x61, 0x74,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x73, 0x52, 0x0d, 0x53, 0x65, 0x76, 0x65, 0x6e, 0x44, 0x61, 0x79, 0x73, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x4a, 0x0a, 0x16, 0x53, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x30, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x44, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x22, 0x3c, 0x0a, 0x14, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d,
	0x73, 0x67, 0x32, 0xd7, 0x01, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12,
	0x6c, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x76, 0x65, 0x6e, 0x44,
	0x61, 0x79, 0x73, 0x53, 0x74, 0x61, 0x74, 0x12, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74,
	0x61, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x65, 0x76, 0x65, 0x6e, 0x44, 0x61, 0x79, 0x73, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x5f, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x76, 0x65, 0x6e,
	0x44, 0x61, 0x79, 0x73, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x5d, 0x0a,
	0x0f, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74,
	0x61, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x29, 0x5a, 0x27,
	0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x3b, 0x73, 0x74,
	0x61, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_stat_user_stat_user_proto_rawDescOnce sync.Once
	file_api_stat_user_stat_user_proto_rawDescData = file_api_stat_user_stat_user_proto_rawDesc
)

func file_api_stat_user_stat_user_proto_rawDescGZIP() []byte {
	file_api_stat_user_stat_user_proto_rawDescOnce.Do(func() {
		file_api_stat_user_stat_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_stat_user_stat_user_proto_rawDescData)
	})
	return file_api_stat_user_stat_user_proto_rawDescData
}

var file_api_stat_user_stat_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_stat_user_stat_user_proto_goTypes = []any{
	(*DayStatistics)(nil),               // 0: api.stat_user.DayStatistics
	(*GetUserSevenDaysStatRequest)(nil), // 1: api.stat_user.GetUserSevenDaysStatRequest
	(*GetUserSevenDaysStatReply)(nil),   // 2: api.stat_user.GetUserSevenDaysStatReply
	(*SetUserStatInfoRequest)(nil),      // 3: api.stat_user.SetUserStatInfoRequest
	(*SetUserStatInfoReply)(nil),        // 4: api.stat_user.SetUserStatInfoReply
}
var file_api_stat_user_stat_user_proto_depIdxs = []int32{
	0, // 0: api.stat_user.GetUserSevenDaysStatReply.SevenDaysData:type_name -> api.stat_user.DayStatistics
	0, // 1: api.stat_user.SetUserStatInfoRequest.Data:type_name -> api.stat_user.DayStatistics
	1, // 2: api.stat_user.StatUser.GetUserSevenDaysStat:input_type -> api.stat_user.GetUserSevenDaysStatRequest
	3, // 3: api.stat_user.StatUser.SetUserStatInfo:input_type -> api.stat_user.SetUserStatInfoRequest
	2, // 4: api.stat_user.StatUser.GetUserSevenDaysStat:output_type -> api.stat_user.GetUserSevenDaysStatReply
	4, // 5: api.stat_user.StatUser.SetUserStatInfo:output_type -> api.stat_user.SetUserStatInfoReply
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_stat_user_stat_user_proto_init() }
func file_api_stat_user_stat_user_proto_init() {
	if File_api_stat_user_stat_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_stat_user_stat_user_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*DayStatistics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_stat_user_stat_user_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserSevenDaysStatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_stat_user_stat_user_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserSevenDaysStatReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_stat_user_stat_user_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SetUserStatInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_stat_user_stat_user_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*SetUserStatInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_stat_user_stat_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_stat_user_stat_user_proto_goTypes,
		DependencyIndexes: file_api_stat_user_stat_user_proto_depIdxs,
		MessageInfos:      file_api_stat_user_stat_user_proto_msgTypes,
	}.Build()
	File_api_stat_user_stat_user_proto = out.File
	file_api_stat_user_stat_user_proto_rawDesc = nil
	file_api_stat_user_stat_user_proto_goTypes = nil
	file_api_stat_user_stat_user_proto_depIdxs = nil
}
