// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"AI_Service/internal/biz"
	"AI_Service/internal/conf"
	"AI_Service/internal/data"
	"AI_Service/internal/server"
	"AI_Service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	aiCloudflareRepo := data.NewAICloudflareRepo(dataData)
	aiCloudflareUsecase := biz.NewAICloudflareUsecase(aiCloudflareRepo)
	aiCloudflareService := service.NewAICloudflareService(aiCloudflareUsecase)
	grpcServer := server.NewGRPCServer(confServer, aiCloudflareService, logger)
	app := newApp(logger, grpcServer, dataData)
	return app, func() {
		cleanup()
	}, nil
}
