// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.24.3
// source: articles/error_def.proto

package articles

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArticleErrorReason int32

const (
	ArticleErrorReason_ERR_ARTICLE_NOT_EXIST           ArticleErrorReason = 0
	ArticleErrorReason_ERR_ARTICLE_INVALID_ID_OR_TITLE ArticleErrorReason = 1
	ArticleErrorReason_SUCCESS                         ArticleErrorReason = 2
)

// Enum value maps for ArticleErrorReason.
var (
	ArticleErrorReason_name = map[int32]string{
		0: "ERR_ARTICLE_NOT_EXIST",
		1: "ERR_ARTICLE_INVALID_ID_OR_TITLE",
		2: "SUCCESS",
	}
	ArticleErrorReason_value = map[string]int32{
		"ERR_ARTICLE_NOT_EXIST":           0,
		"ERR_ARTICLE_INVALID_ID_OR_TITLE": 1,
		"SUCCESS":                         2,
	}
)

func (x ArticleErrorReason) Enum() *ArticleErrorReason {
	p := new(ArticleErrorReason)
	*p = x
	return p
}

func (x ArticleErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArticleErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_articles_error_def_proto_enumTypes[0].Descriptor()
}

func (ArticleErrorReason) Type() protoreflect.EnumType {
	return &file_articles_error_def_proto_enumTypes[0]
}

func (x ArticleErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArticleErrorReason.Descriptor instead.
func (ArticleErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_articles_error_def_proto_rawDescGZIP(), []int{0}
}

var File_articles_error_def_proto protoreflect.FileDescriptor

var file_articles_error_def_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x5f, 0x64, 0x65, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x70, 0x69, 0x2e,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x1a, 0x13, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x73, 0x0a,
	0x12, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x15, 0x45, 0x52, 0x52, 0x5f, 0x41, 0x52, 0x54, 0x49, 0x43,
	0x4c, 0x45, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x10, 0x00, 0x1a, 0x04,
	0xa8, 0x45, 0x94, 0x03, 0x12, 0x29, 0x0a, 0x1f, 0x45, 0x52, 0x52, 0x5f, 0x41, 0x52, 0x54, 0x49,
	0x43, 0x4c, 0x45, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x49, 0x44, 0x5f, 0x4f,
	0x52, 0x5f, 0x54, 0x49, 0x54, 0x4c, 0x45, 0x10, 0x01, 0x1a, 0x04, 0xa8, 0x45, 0x90, 0x03, 0x12,
	0x11, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x02, 0x1a, 0x04, 0xa8, 0x45,
	0xc8, 0x01, 0x42, 0x1c, 0x5a, 0x1a, 0x62, 0x6c, 0x6f, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x3b, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_articles_error_def_proto_rawDescOnce sync.Once
	file_articles_error_def_proto_rawDescData = file_articles_error_def_proto_rawDesc
)

func file_articles_error_def_proto_rawDescGZIP() []byte {
	file_articles_error_def_proto_rawDescOnce.Do(func() {
		file_articles_error_def_proto_rawDescData = protoimpl.X.CompressGZIP(file_articles_error_def_proto_rawDescData)
	})
	return file_articles_error_def_proto_rawDescData
}

var file_articles_error_def_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_articles_error_def_proto_goTypes = []any{
	(ArticleErrorReason)(0), // 0: api.articles.ArticleErrorReason
}
var file_articles_error_def_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_articles_error_def_proto_init() }
func file_articles_error_def_proto_init() {
	if File_articles_error_def_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_articles_error_def_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_articles_error_def_proto_goTypes,
		DependencyIndexes: file_articles_error_def_proto_depIdxs,
		EnumInfos:         file_articles_error_def_proto_enumTypes,
	}.Build()
	File_articles_error_def_proto = out.File
	file_articles_error_def_proto_rawDesc = nil
	file_articles_error_def_proto_goTypes = nil
	file_articles_error_def_proto_depIdxs = nil
}
