name: Docker image CI

on:
    push:
        branches:
            - "main"

jobs:
    build_blog:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
                
            - name: Build the Docker image
              run: docker build ./blog/. --tag tmp-image

            - name: Tag and Push the Docker image
              run: |
                docker tag tmp-image lockheedlee/kratos-blog-micro-article:latest
                docker push lockheedlee/kratos-blog-micro-article:latest
    build_category:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
                
            - name: Build the Docker image
              run: docker build ./category/. --tag tmp-image

            - name: Tag and Push the Docker image
              run: |
                docker tag tmp-image lockheedlee/kratos-blog-micro-category:latest
                docker push lockheedlee/kratos-blog-micro-category:latest
    build_user:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
                
            - name: Build the Docker image
              run: docker build ./user/. --tag tmp-image

            - name: Tag and Push the Docker image
              run: |
                docker tag tmp-image lockheedlee/kratos-blog-micro-user:latest
                docker push lockheedlee/kratos-blog-micro-user:latest
    build_stat_user:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
                
            - name: Build the Docker image
              run: docker build ./statistics_user/. --tag tmp-image

            - name: Tag and Push the Docker image
              run: |
                docker tag tmp-image lockheedlee/kratos-blog-micro-stat-user:latest
                docker push lockheedlee/kratos-blog-micro-stat-user:latest
    build_gateway:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
                
            - name: Build the Docker image
              run: docker build ./gateway/. --tag tmp-image

            - name: Tag and Push the Docker image
              run: |
                docker tag tmp-image lockheedlee/kratos-blog-micro-gateway:latest
                docker push lockheedlee/kratos-blog-micro-gateway:latest    
    ssh_deploy:
        runs-on: ubuntu-latest
        needs: [build_user,build_blog,build_category,build_gateway,build_stat_user]
        steps:
            - name: deploy
              uses: easingthemes/ssh-deploy@v5.1.0
              with:
                SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
                REMOTE_HOST: ${{secrets.REMOTE_HOST}}
                REMOTE_USER: ${{secrets.REMOTE_USER}}
                REMOTE_PORT: ${{secrets.SERVER_PORT}}
                SCRIPT_AFTER: |
                  cd ${{secrets.DOCKER_COMPOSE_PATH}}
                  echo ${{secrets.PASSWD}} | sudo -S /bin/bash deploy.sh