name: Docker image CI

on:
    push:
        branches:
            - "main"

jobs:
    build_blog:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Build the Docker image
              run: docker build ./blog --file Dockerfile --tag lockheedlee/kratos-blog-micro-article:latest

            - name: Push the Docker image
              run: docker push lockheedlee/kratos-blog-micro-article
            